# 设置开发模式
spring:
  profiles:
    active: dev
  # 配置mysql数据源
  datasource:
    username: root
    password: COfdRTgjYlbPfu+JF40FuwGXqUHOM8OjbRoXFika6rBiWFVhjE2Ru2pAiGhs4lpv1xO7/tYzZB3y7IGwytS7Pw==
    url: jdbc:mysql://localhost:3306/miniProgramme?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid连接池
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 1 from dual
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      keep-alive: true
      # 密码加密
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJo76HY0oBTN4MJQDlshA0aySy3gUemdLtICPmmtUP9s8sewW/7jA35AExFRFcxmsviZEscSkBCGbRgwZh02iAUCAwEAAQ==
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      location:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

# 配置日志（默认控制台输出）
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      column-underline: true
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #查询时为null字段不加入，比如QueryWrapper中的应用
    call-setters-on-nulls: true
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    #配置mybatis的配置文件扫描路径
  mapper-locations: classpath:mapper/*.xml
  # 配置包的别名
  type-aliases-package: com.zys.pojo

# tomcat 端口
server:
  port: 9998

